import { test, expect } from "@playwright/test";
import Database from "better-sqlite3";
import path from "node:path";
import { emptyLearning } from "../../src/features/learning";

test("records partial work and optional assessment, edits it, persists on reload and excludes previews from coverage",async({page,request},info)=>{
  const state=structuredClone(emptyLearning);
  state.courses=[{id:"987654",title:"测试课程 · 电路与系统（合成验收数据）",url:"https://moodle.nottingham.ac.uk/course/view.php?id=987654",selected:true,syncedAt:new Date().toISOString(),topics:[{id:"section-1",title:"Lecture 1 · 线性电路",included:true,taught:false,resources:[{id:"folder:1",title:"Lecture slides",kind:"folder",url:"https://moodle.nottingham.ac.uk/mod/folder/view.php?id=1"},{id:"assign:2",title:"Coursework 1",kind:"assign",url:"https://moodle.nottingham.ac.uk/mod/assign/view.php?id=2",coursework:{status:"draft",statusText:"Draft (not submitted)",due:"9月20日 16:00",files:["report.pdf"],modified:"9月11日",grading:"Not graded",grade:"",checkedAt:new Date().toISOString()}}]},{id:"section-2",title:"Lecture 2 · 信号分析",included:false,taught:false,resources:[]}]},{id:"987655",title:"测试课程 · 控制系统（合成验收数据）",url:"https://moodle.nottingham.ac.uk/course/view.php?id=987655",selected:true,syncedAt:new Date().toISOString(),topics:[{id:"section-1",title:"Lecture 1 · Feedback",included:true,taught:true,resources:[]}]}];
  state.notices=[{id:"new:987654:assign:2",courseId:"987654",title:"电路与系统 · 新 coursework：Coursework 1",url:"https://moodle.nottingham.ac.uk/mod/assign/view.php?id=2",createdAt:new Date().toISOString(),read:false}];
  const db=new Database(path.resolve('.test-data/e2e/data/app.sqlite'));
  db.prepare("INSERT INTO learning_workspace(id,payload) VALUES(1,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload").run(JSON.stringify(state));db.close();
  await request.put("/api/settings",{data:{appearance:"liquid",theme:"light"}});
  await page.goto('/learning');
  await expect(page.getByRole('button',{name:/测试课程 · 电路与系统/})).toBeVisible();
  await expect(page.getByRole('button',{name:/测试课程 · 控制系统/})).toBeVisible();
  await expect(page.getByRole('img',{name:/电路与系统.*待确认学习位置/})).toBeVisible();
  const tabs=page.getByRole('tab');
  await expect(tabs.nth(0)).toHaveText('我的课程');await expect(tabs.nth(1)).toHaveText('Coursework 待办');await expect(tabs.nth(2)).toHaveText('复习');
  await page.getByRole('tab',{name:/Coursework 待办/}).click();
  await expect(page.getByText('已上传草稿 · 尚未提交')).toBeVisible();
  await expect(page.getByText('report.pdf')).toBeVisible();
  await page.getByRole('tab',{name:/消息/}).click();
  await expect(page.getByText(/新 coursework：Coursework 1/)).toBeVisible();
  await page.getByRole('tab',{name:/我的课程/}).click();
  await page.getByRole('button',{name:/测试课程 · 电路与系统/}).click();
  await page.getByLabel('已学完到哪个主题').selectOption('section-1');
  await page.reload();
  await expect(page.getByLabel('已学完到哪个主题')).toHaveValue('section-1');
  const topic=page.locator('.learning-topic').filter({hasText:'Lecture 1'});
  await topic.getByRole('button',{name:'记录复习'}).click();
  let dialog=page.getByRole('dialog');
  await expect(dialog.getByLabel('本次动作')).toHaveValue('review');
  await dialog.getByLabel('学到哪里').fill('第 12 页');
  await dialog.getByLabel('实际分钟').fill('20');
  await dialog.getByRole('button',{name:'保存记录'}).click();await expect(dialog).toBeHidden();
  await expect(page.locator('.learning-stats')).toContainText('0/1');
  await topic.getByRole('button',{name:/标为重要/}).click();
  await expect(page.locator('.learning-stats').filter({hasText:'重要 Part'})).toContainText('1');
  await page.getByRole('tab',{name:'学习记录'}).click();
  const history=page.locator('.learning-task').filter({hasText:'第 12 页'});
  await history.getByRole('button',{name:'修改记录'}).click();dialog=page.getByRole('dialog');
  await dialog.getByLabel('本次完成情况').selectOption('complete');
  await dialog.getByRole('button',{name:'保存记录'}).click();await expect(dialog).toBeHidden();
  const saved=(await (await request.get('/api/learning')).json()).data;
  expect(saved.records).toHaveLength(1);expect(saved.courses[0].topics[0].important).toBe(true);
  await page.reload();await expect(page.locator('.learning-stats')).toContainText('1/1');
  for(const appearance of ['liquid','notebook','neo']){
    await page.setViewportSize({width:1440,height:1000});
    await request.put('/api/settings',{data:{appearance}});await page.reload();
    await expect(topic).toBeVisible();
    await expect(page.locator("html")).toHaveAttribute("data-appearance", appearance);
    await expect(page.locator(".learning-stats")).toContainText("1/1");
    await page.screenshot({path:info.outputPath(`learning-${appearance}.png`),fullPage:true,animations:"disabled"});
    await page.setViewportSize({width:390,height:844});
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
    await page.screenshot({path:info.outputPath(`learning-${appearance}-mobile.png`),fullPage:true,animations:"disabled"});
  }
  await page.setViewportSize({width:1440,height:1000});
  await page.getByRole('tab',{name:'复习',exact:true}).click();await expect(page.getByRole('heading',{name:'考试前复习'})).toBeVisible();
  await expect(page.locator('.learning-review-part')).toHaveCount(2);await page.locator('.learning-review-part').filter({hasText:'Lecture 1 · 线性电路'}).locator('summary').click();await expect(page.getByText('Lecture slides')).toBeVisible();
  await page.goto('/');await expect(page.getByText(/考试前已复习 1\/2 个 Part/)).toBeVisible();
});
