import { useEffect, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { ResponsiveContainer, LineChart, Line, XAxis, YAxis, Tooltip } from "recharts";
import { Check, Plus, TrendUp } from "@phosphor-icons/react";
import { api } from "../api";
import { useWorkspace } from "../WorkspaceContext";
import { MonthCalendar } from "../components/MonthCalendar";
import { formatDate, localDate } from "../utils";
import { Badge, Button, EmptyState, EntityForm, Modal, PageHeader, Section, type FieldDefinition } from "../components/ui";
import { ModuleArtwork } from "../components/ModuleArtwork";

const dayMs = 86_400_000;
export function FitnessPage() {
  const { data, run } = useWorkspace(); const [params,setParams]=useSearchParams();
  const [dialog,setDialog]=useState<{type:string;date?:string}|null>(null); const [calendarMonth,setCalendarMonth]=useState(localDate().slice(0,7)); const [selectedDate,setSelectedDate]=useState(localDate());
  useEffect(()=>{const value=params.get("new");if(value)setDialog({type:value==="workout"?"plan":value,date:localDate()});},[params]);
  const close=()=>{setDialog(null);setParams({});};
  const recurringPlans=data.workoutTemplates.filter(plan=>Boolean(plan.starts_on)); const selectedPlans=recurringPlans.filter(plan=>planOccursOn(plan,selectedDate)); const selectedWorkouts=data.workouts.filter(item=>item.workout_date===selectedDate);
  const recentCutoff=shiftDate(localDate(),-6); const recentWorkouts=[...data.workouts].filter(item=>item.workout_date>=recentCutoff&&item.workout_date<=localDate()).sort((a,b)=>b.workout_date.localeCompare(a.workout_date));
  const weightRecords=[...data.bodyMetrics].filter(item=>Number.isFinite(Number(item.weight))).sort((a,b)=>a.metric_date.localeCompare(b.metric_date)).slice(-12); const weightChart=weightRecords.map(item=>({date:item.metric_date.slice(5),weight:Number(item.weight)}));
  const completePlan=(plan:any)=>run(()=>api.create("workouts",{template_id:plan.id,name:plan.name,body_part:plan.body_part,workout_date:selectedDate,status:"completed",completed_at:new Date().toISOString()}));
  return <div><PageHeader icon={<ModuleArtwork module="fitness"/>} eyebrow="训练与身体数据" title="健身计划" description="在日历安排循环训练，完成后轻点记录。" actions={<Button variant="secondary" onClick={()=>setDialog({type:"metric"})}><TrendUp size={17}/>记录身体数据</Button>}/>
    <Section title="训练日历" description="点选一天，创建循环计划或记录当天完成情况。"><MonthCalendar month={calendarMonth} selectedDate={selectedDate} onMonthChange={setCalendarMonth} onSelectDate={date=>{setSelectedDate(date);setCalendarMonth(date.slice(0,7));}} renderDay={date=><WorkoutCalendarDay date={date} data={data}/>}/>
      <div className="calendar-selected-detail"><header><div><span>选中日期</span><strong>{formatDate(selectedDate)}</strong></div><Button size="sm" onClick={()=>setDialog({type:"plan",date:selectedDate})}><Plus size={14}/>在这天添加循环计划</Button></header>
        {selectedPlans.length||selectedWorkouts.length?<div className="calendar-detail-list">{selectedPlans.map(plan=>{const workout=selectedWorkouts.find(item=>item.template_id===plan.id);return <article key={plan.id}><div><strong>{plan.name}</strong><small>{plan.body_part||"自主训练"} · 每 {plan.repeat_weeks||1} 周</small></div>{workout?<Badge tone="success">已完成</Badge>:<Button size="sm" variant="secondary" onClick={()=>void completePlan(plan)}><Check size={14}/>标记完成</Button>}</article>;})}{selectedWorkouts.filter(item=>!selectedPlans.some(plan=>plan.id===item.template_id)).map(item=><article key={item.id}><div><strong>{item.name}</strong><small>{item.body_part||"自主训练"}</small></div><Badge tone={item.status==="completed"?"success":"neutral"}>{item.status==="completed"?"已完成":"已安排"}</Badge></article>)}</div>:<p className="quiet-line">这一天还没有训练安排。</p>}</div>
    </Section>
    <div className="fitness-grid"><Section title="循环计划" description="计划会按选定的星期和周期间隔显示在日历中。">{recurringPlans.length?<div className="fitness-plan-list">{recurringPlans.map(plan=><article key={plan.id}><div><strong>{plan.name}</strong><small>{plan.body_part||"自主训练"}</small></div><span>{weekdayName(plan.weekday)} · 每 {plan.repeat_weeks||1} 周</span></article>)}</div>:<EmptyState title="还没有循环计划" description="在日历中点选第一次训练的日期即可创建。"/>}</Section>
      <Section title="体重记录" description={weightRecords.length?`最近 ${weightRecords.length} 次真实记录`:"只显示你实际保存的体重"}>{weightChart.length===1?<div className="weight-single"><strong>{weightChart[0].weight}</strong><span>kg</span><small>{formatDate(weightRecords[0].metric_date)}</small></div>:weightChart.length>1?<div className="chart-wrap weight-chart"><ResponsiveContainer width="100%" height={240}><LineChart data={weightChart} margin={{top:12,right:16,bottom:8,left:0}}><XAxis dataKey="date" tickLine={false} axisLine={false} tick={{fontSize:11}}/><YAxis domain={["dataMin - 1","dataMax + 1"]} tickLine={false} axisLine={false} tick={{fontSize:10}} width={38}/><Tooltip formatter={value=>[`${value} kg`,"体重"]} labelFormatter={label=>`日期 ${label}`}/><Line type="monotone" dataKey="weight" stroke="var(--accent)" strokeWidth={2.5} dot={{fill:"var(--surface)",stroke:"var(--accent)",strokeWidth:2}}/></LineChart></ResponsiveContainer></div>:<EmptyState title="还没有体重记录" description="记录体重后，这里会显示真实变化。"/>}</Section></div>
    <Section title="近期训练" description="只显示最近 7 天的训练记录">{recentWorkouts.length?<div className="history-table">{recentWorkouts.map(item=><article key={item.id}><div><strong>{item.name}</strong><small>{formatDate(item.workout_date)} · {item.body_part||"自主训练"}</small></div><Badge tone={item.status==="completed"?"success":"neutral"}>{item.status==="completed"?"已完成":"已安排"}</Badge>{item.feeling?.trim()?<p>{item.feeling}</p>:null}</article>)}</div>:<p className="quiet-line">最近 7 天还没有训练记录。</p>}</Section><FitnessDialog dialog={dialog} close={close} run={run}/></div>;
}
function FitnessDialog({dialog,close,run}:any){if(!dialog)return null;const fields:Record<string,FieldDefinition[]>={plan:[{name:"name",label:"计划名称",required:true,placeholder:"例如：周一训练"},{name:"body_part",label:"训练内容",required:true,placeholder:"例如：胸部 + 手臂"},{name:"repeat_weeks",label:"循环周期（周）",type:"number",required:true}],metric:[{name:"metric_date",label:"日期",type:"date",required:true},{name:"weight",label:"体重 kg",type:"number",step:"0.1"},{name:"upper_arm",label:"上臂围 cm",type:"number",step:"0.1"},{name:"chest",label:"胸围 cm",type:"number",step:"0.1"},{name:"body_fat",label:"体脂 %",type:"number",step:"0.1"},{name:"notes",label:"训练备注",type:"textarea"}]};const isPlan=dialog.type==="plan";const date=dialog.date||localDate();const defaults=isPlan?{starts_on:date,weekday:isoWeekday(date),repeat_weeks:1,notes:""}:{metric_date:localDate()};return <Modal open title={isPlan?`添加循环计划 · ${formatDate(date)}`:"记录身体数据"} onClose={close}><EntityForm fields={fields[dialog.type]||fields.metric} initial={defaults} onCancel={close} onSubmit={async values=>{await run(()=>api.create(isPlan?"workoutTemplates":"bodyMetrics",{...defaults,...values}));close();}}/></Modal>;}
function WorkoutCalendarDay({date,data}:{date:string;data:any}){const plans=data.workoutTemplates.filter((plan:any)=>planOccursOn(plan,date));const workouts=data.workouts.filter((item:any)=>item.workout_date===date);const entries=plans.map((plan:any)=>({key:plan.id,title:plan.body_part||plan.name,completed:workouts.some((item:any)=>item.template_id===plan.id&&item.status==="completed")}));workouts.filter((item:any)=>!plans.some((plan:any)=>plan.id===item.template_id)).forEach((item:any)=>entries.push({key:item.id,title:item.body_part||item.name,completed:item.status==="completed"}));return <>{entries.slice(0,2).map((entry:any)=><div className={`calendar-entry workout-${entry.completed?"completed":"planned"}`} key={entry.key}><strong>{entry.title}</strong><span>{entry.completed?"已完成":"计划"}</span></div>)}{entries.length>2?<small className="calendar-more">另有 {entries.length-2} 项</small>:null}</>;}
export function planOccursOn(plan:any,date:string){if(!plan.starts_on)return false;const weekday=Number(plan.weekday);if(weekday!==isoWeekday(date))return false;const start=plan.starts_on;if(date<start)return false;const weeks=Math.floor((parseDate(date).getTime()-parseDate(start).getTime())/dayMs/7);return weeks%Math.max(1,Number(plan.repeat_weeks)||1)===0;}
function parseDate(value:string){const [y,m,d]=value.split("-").map(Number);return new Date(y,m-1,d,12);} function isoWeekday(value:string){const day=parseDate(value).getDay();return day===0?7:day;} function shiftDate(value:string,amount:number){const date=parseDate(value);date.setDate(date.getDate()+amount);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;} function weekdayName(value:unknown){return `周${["一","二","三","四","五","六","日"][Math.max(1,Number(value)||1)-1]}`;}
